---
# tasks file for osp-rbac

  - name: get the osp auth
    os_auth:
      region_name: "{{ region }}"
      cert: "{{ user_cert }}"
      key: "{{ user_key }}"
      cacert: "{{ user_cacert }}"
      endpoint_type: "{{ user_endpoint }}"
    register: user_auth

  - name: create a domain
    os_keystone_domain: 
      name: "{{ user_domain }}"
      enabled: "{{ domain_status }}"
      state: "{{ domain_state }}"
      region_name: "{{ region }}"
      key: "{{ user_key }}"
      cert: "{{ user_key }}"
      cacert: "{{ user_cacert }}"





  - name: create users
    os_user:
    name: "{{ os_user }}"
    state: "{{ user_status }}"
    email: "{{ user_email }}"
    password: "{{ user_passwd }}"
    domain: "{{ user_domain }}"
    default: "{{ user_project }}"
    endpoint_type: "{{ user_endpoint }}"
    key: " {{ user_key }}"
    cacert: "{{ user_cacert }}"


